import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar } from "./navbar/page";
import Providers from "./Redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
